services:
  auth-service:
    build:
      args:
      - NODE_ENV=production
      context: /services/auth-service
      target: production
    command: pnpm start
    ports:
      - 4000:4000
    environment:
      - NODE_ENV=production
    networks:
      - public
      - private
  api-gateway:
    build:
      args:
      - NODE_ENV=production
      context: /apps/api-gateway
      target: production
    command: pnpm start
    ports:
      - 4001:4001
    environment:
      - NODE_ENV=production
    networks:
      - public
      - private
  web:
    build:
      args:
      - NODE_ENV=production
      context: .
      dockerfile: apps/web/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    depends_on:
      auth-service:
        condition: service_started
      api-gateway:
        condition: service_started
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
  public:
  private:
